title: Brut de Thé
description: >
  Collectif qui explore le monde du thé de tradition Chinoise. Nous vous proposons des ressources pour apprendre, approfondir ou découvrir les types de thé : vert, blanc, jaune, wulong, rouge, noir et Pu'Er et les ustensiles : Théière, Gaiwan et autres.
author: pntbr
email: pntbr@scopyleft.fr
repository: brutdethe/site.git

encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
future: true
jailed: false
gfm_quirks: paragraph_end

defaults:
  - scope:
      path: ""
    values:
      layout: article

collections_dir: ressources

collections:
  pages:
    output: true
    order:
      - nos-valeurs.md
      - faq.md
      - liens.md
      - lieux-prevenants.md
      - contribuer.md
      - agenda.md
  base:
    description: Quelques articles pour se repérer et s'initier au monde du Thé
    output: true
  expert:
    description: Vous trouverez là, des articles variés pour creuser des sujets spécifiques
    output: true
  intermediaire:
    description: Pour aller plus loin
    output: true
  traduction:
    description: Collection d'articles sélectionnés et traduits de l'anglais ou du chinois
    output: true

plugins:
  - jekyll-remote-theme
  - jekyll-github-metadata
  - jekyll-relative-links
  - jekyll-titles-from-headings
