titre: Brut de Thé
author: pntbr
email: pntbr@scopyleft.fr
description: >
  Daktary est un éco-système d'outils permmettant de faciliter l'édition et la 
  publication de ressources *markdown* hébergées sur *github* ou *gitlab*.

encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
future: true
jailed: false
gfm_quirks: paragraph_end

defaults:
  - scope:
      path: ""
    values:
      layout: article

collections_dir: ressources

collections:
  pages:
    output: true
  base:
    output: true
  expert:
    output: true
  intermediaire:
    output: true
  traduction:
    output: true

plugins:
  - jekyll-remote-theme
  - jekyll-github-metadata
  - jekyll-relative-links
  - jekyll-titles-from-headings
